baseURL = 'https://soumyadghosh.github.io/website/'
languageCode = 'en-us'
title = "Soumya's Web"
copyright = "Soumyadeep Ghosh. All rights reserved."
theme = 'PaperMod'
showrss = false
sectionPagesMenu = "main"
enableEmoji = true

[menu]
  [[menu.main]]
  name = "About"
  weight = 10
  url = "/about"

[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowShareButtons = true
  env = 'production'
  comments = true
  mainSections = ["blog", "interns"]
  [params.scrollToTop]
  enabled = true

  [params.editPost]
  URL = "https://github.com/soumyaDghosh/website/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.homeInfoParams]
  Title = "Namaskar World."
  Content = "Happy Exploring!!"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:soumyadeepghosh2004+website@zohomail.in"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/soumyaDghosh"

  [[params.socialIcons]]
  name = "gitlab"
  url = "https://gitlab.com/soumyaDghosh"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/soumyadghosh"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.social/@soumyadghosh"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/s0umyad"

  [[params.socialIcons]]
  name = "matrix"
  url = "https://matrix.to/#/@soumyatheman:matrix.org"

  [[params.socialIcons]]
  name = "telegram"
  url = "https://telegram.me/soumyatheman"

  [[params.socialIcons]]
  name = "kofi"
  url = "https://ko-fi.com/soumyadghosh"

  [[params.socialIcons]]
  name = "paypal"
  url = "https://paypal.me/soumyaDghosh?country.x=IN&locale.x=en_GB"  

  [[params.socialIcons]]
  name = "rss"
  title = "RSS"
  url = "https://soumyadghosh.github.io/website/index.xml"


[outputs]
home = ["HTML", "RSS", "JSON"]
